## Matrix Algebra

Pada bagian ini kita melihat Aljabar Matriks dan beberapa sifat umumnya. Kita juga akan melihat bagaimana operasi yang melibatkan matriks dihubungkan dengan sistem persamaan linier.

**matriks** a adalah larik bilangan dua dimensi. Saat kita melakukan komputasi dengan matriks menggunakan NumPy, kita akan menggunakan array seperti yang kita lakukan sebelumnya. Mari kita tuliskan beberapa contoh matriks dan beri nama.

$$
\begin{equation}
A = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] \hspace{1cm}
B = \left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right] \hspace{1cm}
C = \left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right] \hspace{1cm}
D = \left[ \begin{array}{r} 2 \\ 6 \end{array}\right]
\end{equation}
$$

Saat mendiskusikan matriks, kita biasanya membicarakan dimensi, atau bentuknya, dengan menentukan jumlah baris dan kolom. Jumlah baris biasanya dicantumkan terlebih dahulu. Sebagai contoh, $A$ dan $C$ adalah matriks $2\times 2$, $B$ adalah matriks $2 \times 3$, dan $D$ adalah matriks $2 \times 1 $. Matriks yang hanya memiliki 1 kolom, seperti $D$, biasa disebut **vektor**. Kita juga akan mematuhi konvensi ini, namun perlu diingat bahwa ketika kita membuat pernyataan tentang matriks, kita juga membuat pernyataan tentang vektor meskipun kita tidak menyebutkannya secara eksplisit. Kita juga akan mengadopsi konvensi umum penggunaan huruf besar untuk memberi nama matriks.

Penting juga untuk membicarakan entri individual matriks. Notasi umum untuk ini adalah huruf kecil dengan subskrip untuk menunjukkan posisi entri dalam matriks. Jadi $b_{12}$ mengacu pada 0 pada baris pertama dan kolom kedua matriks $B$. Jika kita berbicara tentang posisi umum, kita mungkin menggunakan variabel di subskrip, seperti $a_{ij}$.

Mari kita buat matriks ini sebagai array NumPy sebelum berdiskusi lebih lanjut.

In [2]:
import numpy as np
A = np.array([[1, 3],[2,1]])
B = np.array([[3, 0, 4],[-1, -2, 1]])
C = np.array([[-2, 1],[4, 1]])
D = np.array([[2],[6]])
print(A)

[[1 3]
 [2 1]]


Bagian tersebut akan digunakan  untuk mengakses dimensi array kita. Saat array dibuat, informasi ini disimpan sebagai bagian dari objek array dan dapat diakses dengan metode yang disebut $\texttt{shape}$. Jika $\texttt{B}$ adalah sebuah array, objek $\texttt{B.shape}$ itu sendiri adalah sebuah array yang memiliki dua nilai masukan. Yang pertama (*dengan indeks 0!*) adalah jumlah baris, dan yang kedua (*dengan indeks 1!*) adalah jumlah kolom.

In [4]:
print(B)

[[ 3  0  4]
 [-1 -2  1]]


In [ ]:
print("Array B has",B.shape[0],"rows.")
print("Array B has",B.shape[1],"columns.")

Array B has 2 rows.
Array B has 3 columns.


### Operasi-operasi matrik

Ada tiga operasi aljabar untuk matriks yang perlu kita lakukan. Untuk definisi kita, misalkan $A$ dan $C$ adalah matriks $m \times n$,

$B$ adalah matriks $n \times k$, dan $c$ adalah suatu bilangan. Jika membahas aljabar yang melibatkan matriks dan bilangan, bilangan tersebut biasanya disebut dengan **skalar**.

Operasi penjumlahan matrik diantaranya seperti berikut:

1. Matriks dalam bentuk apa pun dapat dikalikan dengan skalar $c$, $d$. Hasilnya adalah semua elemen matrik dikalikan dengan skalar tersebut. Dengan menggunakan notasi subskrip, kita akan ditulis dengan

$$
(cA)_{ij} = ca_{ij}
$$

$$(c+d)A=cA+d{A}$$
$$c(dA)=(cd)A$$
$$c(A+B)=cA+cB$$
$$ A  \quad \text{terdapat} \quad  \text{- A}, \text{sehingga }  A+(- A)=0 $$


2. Matriks yang *ukurannya sama* dapat dijumlahkan. Hasilnya adalah semua elemen yang bersesuaian ditambahkan dan ditulis dalam bentuk.

$$
(A+C)_{ij} = a_{ij} + c_{ij}
$$
$$A+{0}=A \quad \text{dimana ${0}$ matrik nol}$$
$$A+ B= B+ A$$
$$(A+B)+ C=A+(B+C)$$

3. Jika banyaknya kolom dari matrik $A$ adalah sama dengan banyaknya baris matrik $B$, matrik dapat dikalikan dalam dengan bentuk perkalian  $A$, $B$.  Hasilnya adalah matrik $AB$, yang memiliki jumlah baris seperti
 jumlah baris matrik $A$ dan kolom sejumlah kolom matrik $B$.  Elemen-elemen $(AB)_{ij}$ adalah kombinasi elemen baris $i$ dari $A$ dan kolom $j$ dari $B$.
 $$
(AB)_{ij} = \sum_{k=1}^n a_{ik}b_{kj}
$$

  Karakteristik dari **_perkalian matrik_**$A$,$B$,$C$ dan $c$ skalar adalah sebagai berikut
    - $ A({BC})=({AB}) C$
    - $c({AB})=(cA)B=A(cB)$
    - $A(B+ C)={AB}+{AC}$
    - $(B+C)A={BA}+{CA}$

Perlu juga dicatat bahwa sifat komutatif umumnya tidak berlaku untuk perkalian matriks. Misalkan $A$ dan $B$ keduanya merupakan matriks $3\times 3$. **Tidak benar secara umum** bahwa $AB = BA$.
Tetapi ada cara untuk menentukan dua matrik saling komutatif



In [ ]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)

In [ ]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A


⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

In [ ]:
A - A

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [ ]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

In [ ]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [ ]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

In [ ]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
C=A*B;C
D=B*A;D
print(C)
print(D)

Matrix([[23, 13], [51, 29]])
Matrix([[36, 44], [13, 16]])


### Cara menemukan dua matrik bersifat komutatif

In [ ]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

Untuk menunjukkan  ${AB} = {BA}$, kita perlu membuktikan ${AB} - {BA} = 0$

In [ ]:
M = A*B - B*A; M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

Itu artinya
\begin{align}
b g - c f&=0 \\
 a f - b e + b h - d f&=0\\
- a g + c e - c h + d g&=0 \\
- b g + c f&=0
\end{align}

Jika kita menganggap  $a, b, c, d$ sebagai koefisien sistem, kita mengekstrak augmented matrix

In [ ]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d -a, -c], [0, c, -b, 0]]); A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

Melakukan eliminasi  **Gaussian-Jordon** hingga  baris tereduksi

In [ ]:
A_aug.rref()

⎛⎡        a   d    ⎤        ⎞
⎜⎢1  0  - ─ + ─  -1⎥        ⎟
⎜⎢        c   c    ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢        -b       ⎥        ⎟
⎜⎢0  1    ───    0 ⎥, (0, 1)⎟
⎜⎢         c       ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢0  0     0     0 ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎝⎣0  0     0     0 ⎦        ⎠

Penyelesaian secara umum adalah
\begin{align}
e - \frac{a-d}cg - h &=0\\
f - \frac{b}{c} & =0\\
g &= free\\
h & =free
\end{align}

Jika kita tentukan koefisien  $a = 10, b = 12, c = 20, d = 8$, atau $ A = \left[\begin{matrix}10 & 12\\20 & 8\end{matrix}\right]$ maka penyelesaiannya secara umum adalah


\begin{align}
e - .1g - h &=0\\
f - .6 & =0\\
g &= free\\
h & =free
\end{align}
Maka coba memberi penyelesaian jika  $g = h = 1$
\begin{align}
e  &=1.1\\
f & =.6\\
g &=1 \\
h & =1
\end{align}
Dan ini adalah matrik komutatif dari  **commutable matrix of $A$**, kita notasikan dengan  $ B$.

**Latihan soal**
Carilah matrik komutatif dari A ukuran matrik 4 x 4  yang sehingga matrik A*B=B*A

In [ ]:
C = sy.Matrix([[1.1, .6], [1, 1]]);C

⎡1.1  0.6⎤
⎢        ⎥
⎣ 1    1 ⎦

Now we can see that ${AC}={CA}$.

In [ ]:
A = sy.Matrix([[10, 12], [20, 8]])
A*C
C*A


⎡23.0  18.0⎤
⎢          ⎥
⎣30.0  20.0⎦

Operasi ini dikenal  sebagai **perkalian matriks**.

Marilah kita jelaskan dengan beberapa contoh dari Operasi matrik berikut:

1.  Perkalian bilangan(skalar) dan matrik:

$$
\begin{equation}
3A = 3\left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right]
= \left[ \begin{array}{rr} 3 & 9 \\ 6 & 3 \end{array}\right]
\end{equation}
$$

2. Jumlah dari dua matrik yang sama ukurannnya

$$
\begin{equation}
A + C = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] +
\left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right]
= \left[ \begin{array}{rr} -1 & 4 \\ 6 & 2 \end{array}\right]
\end{equation}
$$

3.  Perkalian dari dua matrik:


Contoh perkalian matrik

$$
\begin{equation}
AB = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right]
\left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right]
 = \left[ \begin{array}{rrr} 0 & -6 & 7  \\  5 & -2 & 9  \end{array}\right]
 \end{equation}
$$

Untuk memperjelas apa yang terjadi dalam perkalian matriks, mari kita hitung dua elemen secara detail.

$$
\begin{eqnarray*}
(AB)_{12} & = & 1\times 0 + 3 \times (-2) = -6 \\
(AB)_{23} & = & 2 \times 4 + 1 \times 1 = 9
\end{eqnarray*}
$$

Semua operasi matriks ini ada di NumPy, tetapi kita harus menggunakan simbol $\texttt{@}$ menggantikan  $\texttt{*}$ untuk perkalian matriks.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import scipy as sp
import sympy as sy
sy.init_printing()

In [ ]:
print(3*A,'\n')
print(A+C,'\n')
print(A@B)

[[3 9]
 [6 3]] 

[[-1  4]
 [ 6  2]] 

[[ 0 -6  7]
 [ 5 -2  9]]


In [ ]:
A = np.random.randint(-5,5,size=(3,3))
B = np.random.randint(-5,5,size=(3,3))

print(A@B)
print('\n')
print(B@A)

[[ 35 -11 -14]
 [-28  -7   7]
 [  3  22  13]]


[[ 13  11  -4]
 [  7  44   4]
 [  8 -21 -16]]


### Matrik Transpose
Hal  lainnya yang berguna bagi kita adalah transpose matriks. **transpose** matriks $A$ adalah matriks lain, $A^T$, yang merupakan matrik dimana  kolom-kolomnya merupakan baris-baris matrik $A$. Untuk membuat $A^T$, kita cukup menukar indeks baris dengan indeks kolom untuk setiap elemen-elemen, $a^T_{ij} = a_{ji}$. Dua contoh berikut untuk memperjelas pernyataan diatas.

$$
\begin{equation}
A = \left[ \begin{array}{rrr} 5 & 4 & 0 \\ 1 & 8 & 3 \\ 6 & 7 & 2\end{array}\right] \hspace{1cm}
A^T = \left[ \begin{array}{rrr} 5 & 1 & 6 \\ 4 & 8 & 7 \\ 0 & 3 & 2\end{array}\right] \hspace{1cm}
\end{equation}
$$

$$
\begin{equation}
B = \left[ \begin{array}{rrr} 1 & 2 & 7 & 0 \\ 3 & 1 & 5 & 2 \\ 4 & 9 & 8 & 6\end{array}\right] \hspace{1cm}
B^T = \left[ \begin{array}{rrr} 1 & 3 & 4 \\ 2 & 1 & 9 \\ 7 & 5 & 8 \\ 0 & 2 & 6\end{array}\right] \hspace{1cm}
\end{equation}
$$


Objek array NumPy memiliki metode bernama **transpose** untuk tujuan ini.

In [ ]:
A = np.array([[5, 4, 0],[1, 8, 3],[6, 7, 2]])

## Note that the tranpose method must be called with (), the same as a function with no arguments.
A_T = A.transpose()

print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


Jika matriks $A$ sama dengan transposnya sendiri, matriks tersebut mempunyai sifat simetris terhadap diagonal utamanya. Oleh karena itu matriks $A$ dikatakan **simetris** jika $A = A^T$. Dengan cara yang sama, kita dapat mengatakan bahwa $A$ simetris jika $a_{ij} = a_{ji}$ untuk setiap elemen $a_{ij}$ dalam matriks.

Matriks $P$ di bawah ini adalah salah satu contohnya.

$$
\begin{equation}
P = \left[ \begin{array}{rrr} 1 & 0 & 6 \\ 0 & 3 & 5 \\ 6 & 5 & -2\end{array}\right] \hspace{1cm}
\end{equation}
$$

Sama halnya, kita mengatakan bahwa matrik $A$ adalah **skew-symmetric** jika $A^T = -A$ (jika $a_{ij} = -a_{ji}$ untuk setiap elemen $a_{ij}$ dalam $A$). Matrik $Q$ berikut adalah matrik skew-symmetric.

$$
\begin{equation}
Q = \left[ \begin{array}{rrr} 0 & 1 & -4 \\ -1 & 0 & 5 \\ 4 & -5 & 0\end{array}\right] \hspace{1cm}
\end{equation}
$$


Karakteristk matrik transpose
1. $(A^T)^T$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$

Kita dapat menunjukkan karakteristik terakhir  dengan SymPy, tentukan $A$ dan $B$, kalikan keduanya, lalu ubah urutannya, itu berarti $(AB)^T$

In [ ]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB_tr = AB.transpose(); AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Ubah urutannya masing-masing, lalu kalikan, yaitu $B^TA^T$

In [ ]:
B_tr_A_tr = B.transpose()*A.transpose()
B_tr_A_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [ ]:
AB_tr - B_tr_A_tr

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

### Matrik elementer

Matriks elementer adalah matriks yang dapat diperoleh dari satu operasi baris elementer pada suatu matriks identitas. Seperti:

$$
\left[\begin{matrix}1 & 0 & 0\cr 0 & 1 & 0\cr 0 & 0 & 1\end{matrix}\right]\ \matrix{R_1\leftrightarrow R_2\cr ~\cr ~}\qquad\Longrightarrow\qquad \left[\begin{matrix}0 & 1 & 0\cr 1 & 0 & 0\cr 0 & 0 & 1\end{matrix}\right]
$$

di mana $R_1\leftrightarrow R_2$ berarti menukar baris $1$ dan baris $2$, dan kita nyatakan matriks yang ditransformasikan sebagai ${E}$, lalu kalikan $ E$ ke kiri pada matriks $ A$. Buatlah matrik $A$ terlebih dahulu

In [ ]:
A = sy.randMatrix(3, percent = 80); A # generate a random matrix with 80% of entries being nonzero

⎡74  37  0 ⎤
⎢          ⎥
⎢0   71  19⎥
⎢          ⎥
⎣41  36  19⎦

Buat matriks elementer dengan $R_1\leftrightarrow R_2$

In [ ]:
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);E

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

Yaitu dengan mengalikan $E$ ke $A$, $A$ juga mengganti baris $1$ dan $2$.

In [ ]:
E*A

⎡0   71  19⎤
⎢          ⎥
⎢74  37  0 ⎥
⎢          ⎥
⎣41  36  19⎦

Menambahkan hasil perkalian suatu baris ke baris lain dalam matriks identitas juga menghasilkan matriks elementer.
$$
\left[\begin{matrix}1 & 0 & 0\cr 0 & 1 & 0\cr 0 & 0 & 1\end{matrix}\right]\ \matrix{~\cr ~\cr R_3-7R_1}\qquad\longrightarrow\left[\begin{matrix}1 & 0 & 0\cr 0 & 1 & 0\cr -7 & 0 & 1\end{matrix}\right]
$$

Mari kita verifikasi dengan SymPy.

In [ ]:
A = sy.randMatrix(3, percent = 80); A
E = sy.Matrix([[1, 0, 0], [0, 1, 0], [-7, 0, 1]]); E

⎡1   0  0⎤
⎢        ⎥
⎢0   1  0⎥
⎢        ⎥
⎣-7  0  1⎦

In [ ]:
E*A

⎡ 71    24    55 ⎤
⎢                ⎥
⎢ 44    0     65 ⎥
⎢                ⎥
⎣-497  -163  -298⎦

Kami juga dapat menunjukkan ini dengan jelas  operasi baris  pada $A$.

In [ ]:
EA = sy.matrices.MatrixBase.copy(A)
EA[2,:]=-7*EA[0,:]+EA[2,:]
EA

⎡ 71    24    55 ⎤
⎢                ⎥
⎢ 44    0     65 ⎥
⎢                ⎥
⎣-497  -163  -298⎦

Pada bagian selanjutnya, kita akan melihat ringkasan penting dari perkalian matriks elementer adalah bahwa **matriks yang dapat diinverskan** adalah hasil kali dari serangkaian matriks elementer.

### Matrik Invers

Jika ${AB}={BA}=\mathbf{I}$, $B$ disebut invers matriks $A$, dilambangkan dengan $B= A^{-1}$.

NumPy memiliki fungsi praktis ```np.linalg.inv()``` untuk menghitung matriks invers. Buatlah matrik  $A$

In [ ]:
A = np.round(10*np.random.randn(5,5)); A

array([[  6.,   1., -13.,  -9.,   3.],
       [ -5., -14.,  -3.,  10.,  16.],
       [ 13.,  -9.,   4.,  10.,  13.],
       [ 20.,   5.,   3., -21., -19.],
       [-19.,   5., -11.,  23.,   8.]])

In [ ]:
Ainv = np.linalg.inv(A); Ainv

array([[ 0.01014464, -0.01263389,  0.04600856,  0.02924799,  0.0161636 ],
       [ 0.04141734, -0.13267997,  0.03463886, -0.09214154, -0.02529588],
       [-0.03192687, -0.05033892,  0.01305128, -0.06000397, -0.05106734],
       [-0.0351626 ,  0.0225267 ,  0.02597012,  0.05656958,  0.0602839 ],
       [ 0.05540071, -0.0810608 ,  0.03090247, -0.11809059, -0.06433534]])

Verifikasi apakah keduanya benar-benar invers matrik terhadap satu sama lainnya

In [ ]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)


In [ ]:
A@Ainv

array([[ 1.,  0.,  0., -0.,  0.],
       [-0.,  1.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [ 0., -0., -0., -0.,  1.]])

```-0.``` berarti ada banyak digit setelah titik, tetapi dihilangkan di sini.

Cara yang mudah untuk menghitung invers adalah dengan membuat matriks augmented $[ A\,|\,\mathbf{I}]$, lalu mengalikan deret $E$ yang merupakan operasi baris elementer hingga matriks $A$ menjadi bentuk baris tereduksi, jika full rank berarti $A \rightarrow \mathbf{I}$. Kemudian $\mathbf{I}$ pada RHS pada augmented matrix akan diubah menjadi $A^{-1}$ secara otomatis.


Kita dapat menunjukkan dengan fungsi ```.rref()``` SymPy pada matriks augmented $[A\,|\,I]$.

In [ ]:
I = np.eye(5); I
print(I)

AI = np.hstack((A, I)) # stack the matrix A and I horizontally
AI = sy.Matrix(AI); AI

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


⎡ 6.0    1.0   -13.0  -9.0    3.0   1.0   0    0    0    0 ⎤
⎢                                                          ⎥
⎢-5.0   -14.0  -3.0   10.0   16.0    0   1.0   0    0    0 ⎥
⎢                                                          ⎥
⎢13.0   -9.0    4.0   10.0   13.0    0    0   1.0   0    0 ⎥
⎢                                                          ⎥
⎢20.0    5.0    3.0   -21.0  -19.0   0    0    0   1.0   0 ⎥
⎢                                                          ⎥
⎣-19.0   5.0   -11.0  23.0    8.0    0    0    0    0   1.0⎦

In [ ]:
AI_rref = AI.rref(); AI_rref

⎛⎡1  0  0  0  0  0.0101446396249965   -0.0126338939924791  0.0460085643995489 
⎜⎢                                                                            
⎜⎢0  1  0  0  0  0.0414173398991054   -0.132679966769809   0.0346388624679437 
⎜⎢                                                                            
⎜⎢0  0  1  0  0  -0.0319268694992595  -0.0503389238715581  0.0130512780379739 
⎜⎢                                                                            
⎜⎢0  0  0  1  0  -0.0351625991788772  0.0225266985323332   0.0259701169076658 
⎜⎢                                                                            
⎝⎣0  0  0  0  1  0.0554007087502157   -0.0810607976048577  0.0309024725991387 

 0.0292479863226459   0.0161635984926015 ⎤                 ⎞
                                         ⎥                 ⎟
 -0.0921415413511203  -0.0252958811418664⎥                 ⎟
                                         ⎥                 ⎟
 -0.0600039731750485  -0.0510673392971092⎥, 

Ekstrak blok RHS, ini adalah $A^{-1}$.

In [ ]:
Ainv = AI_rref[0][:,5:];Ainv # extract the RHS block

⎡0.0101446396249965   -0.0126338939924791  0.0460085643995489  0.0292479863226
⎢                                                                             
⎢0.0414173398991054   -0.132679966769809   0.0346388624679437  -0.092141541351
⎢                                                                             
⎢-0.0319268694992595  -0.0503389238715581  0.0130512780379739  -0.060003973175
⎢                                                                             
⎢-0.0351625991788772  0.0225266985323332   0.0259701169076658  0.0565695847430
⎢                                                                             
⎣0.0554007087502157   -0.0810607976048577  0.0309024725991387  -0.118090588391

459   0.0161635984926015 ⎤
                         ⎥
1203  -0.0252958811418664⎥
                         ⎥
0485  -0.0510673392971092⎥
                         ⎥
078   0.0602839014170991 ⎥
                         ⎥
105   -0.0643353359740901⎦

Saya menulis fungsi untuk membulatkan angka float ke digit $4$th, di bagian atas file ini, tetapi ini tidak mutlak diperlukan.

In [ ]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

round_expr(Ainv, 4)

⎡0.0101   -0.0126  0.046   0.0292   0.0162 ⎤
⎢                                          ⎥
⎢0.0414   -0.1327  0.0346  -0.0921  -0.0253⎥
⎢                                          ⎥
⎢-0.0319  -0.0503  0.0131   -0.06   -0.0511⎥
⎢                                          ⎥
⎢-0.0352  0.0225   0.026   0.0566   0.0603 ⎥
⎢                                          ⎥
⎣0.0554   -0.0811  0.0309  -0.1181  -0.0643⎦

Kita dapat memverifikasi apakah $AA^{-1}=\mathbf{I}$

In [ ]:
A = sy.Matrix(A)
round_expr(A*Ainv, 4)

⎡1.0   0    0    0    0 ⎤
⎢                       ⎥
⎢ 0   1.0   0    0    0 ⎥
⎢                       ⎥
⎢ 0    0   1.0   0    0 ⎥
⎢                       ⎥
⎢ 0    0    0   1.0   0 ⎥
⎢                       ⎥
⎣ 0    0    0    0   1.0⎦

Kita mendapatkan $\mathbf{I}$, yang berarti blok RHS memang $A^{-1}$.

#### Karakteristik matrik invers

1. Jika $A$ dan $B$ keduanya dapat diinverskan, maka $(AB)^{-1}=B^{-1}A^{-1}$.
2. Jika $A$ dapat diinverskan, maka $(A^T)^{-1}=(A^{-1})^T$.
3. Jika $A$ dan $B$ keduanya dapat diinverskan dan simetris sehingga $AB=BA$, maka $A^{-1}B$ simetris.

Karakteristik pertama sangat jelas
\begin{align}
ABB^{-1}A^{-1}=AIA^{-1}=I=AB(AB)^{-1}
\end{align}

Trik karakter  kedua adalah menunjukkan hal itu
$$
A^T(A^{-1})^T = I
$$
Kita dapat menggunakan karakteristik matrik transpose
$$
A^T(A^{-1})^T=(A^{-1}A)^T = I^T = I
$$

Karakteristik ketiga menunjukkan
$$
A^{-1}B = (A^{-1}B)^T
$$
Gunakan sifat matrik tanspose
$$
(A^{-1}B)^{T}=B^T(A^{-1})^T=B(A^T)^{-1}=BA^{-1}
$$
Kita menggunakan $AB = BA$ untuk memproses
\begin{align}
AB&=BA\\
A^{-1}ABA^{-1}&=A^{-1}BAA^{-1}\\
BA^{-1}&=A^{-1}B
\end{align}
Dimasukkan ke persaman sebelumnya kita dapatkan
$$
(A^{-1}B)^{T}=BA^{-1}=A^{-1}B
$$

### Aplikasi untuk sistem linier

Contoh perkalian matriks adalah perkalian suatu matrik  dengan vektor yang *tidak diketahui* untuk mendapatkan vektor yang tidak diketahui. Misalkan kita memiliki matrik $A$, $B$ adalah vektor yang diketahui, dan $X$ menjadi vektor yang tidak diketahui, kita dapat menulis persamaan matriks $AX=B$ untuk menggambarkan perkalian matrik. Berikut contohnya.

$$
\begin{equation}
A= \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right] \hspace{1cm}
X= \left[ \begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array}\right] \hspace{1cm}
B= \left[ \begin{array}{r} 0 \\ 10 \\ 7 \\ 4  \end{array}\right] \hspace{1cm}
\end{equation}
$$

$$
\begin{equation}
AX = \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]
\left[ \begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array}\right]=
\left[ \begin{array}{r} 0\\ 10 \\ 7 \\ 4  \end{array}\right]= B
\end{equation}
$$

Kita perhatikan bahwa persamaan matriks tunggal $AX=B$ sebenarnya mewakili sistem persamaan linier.

$$
\begin{eqnarray*}
x_1 + 3x_2 - 2x_3 & = & 0\\
5x_1 + 2x_2 \quad\quad & = & 10 \\
4x_1 + 2x_2 - x_3 & = & 7 \\
2x_1 + 2x_2 \quad\quad & = & 4
\end{eqnarray*}
$$

Dalam hal ini, matriks $A$ dikenal sebagai **matriks koefisien**.

### Matrik identitas

**Matriks identitas** adalah matriks bujursangkan yang sifatnya mirip dengan angka 1 jika dalam perkalian biasa. Matriks identitas, diberi label $I$, terdiri dari matriks dengan memiliki nilai 1 pada elemen-elemen  diagonal utama matrik , dan nol pada elemen lainya. Di bawah ini adalah versi $I$ denga ukuran matrik $4 \times 4$.

$$
\begin{equation}
I = \left[ \begin{array}{ccc} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0\\ 0 & 0 & 0 & 1 \end{array}\right]
\end{equation}
$$

Jika $A$ adalah matriks $4 \times 4$ , perkalian dengan $I$ akan menghasilkan $A$. Selain itu,berlaku juga sifat komutatif pada  perkalian matriknya

$$
\begin{equation}
AI = IA = A
\end{equation}
$$

Fungsi NumPy $\texttt{eye}$ menghasilkan matriks identitas dengan ukuran yang ditentukan. Perhatikan bahwa kita hanya perlu memberikan $\texttt{eye}$ dengan satu parameter karena matriks identitas harus berbentuk bujursangkar. Di sini kami menampilkan perkalian $I$ dengan matriks acak $5\times 5$.

In [ ]:
I = np.eye(5); I
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
R = np.random.randint(-10,10,size=(5,5))
print(R)
print('\n')
print(R@I5)
print('\n')
print(I5@R)

[[ -7  -4  -2   2   7]
 [ -3  -8  -6  -7  -2]
 [  1   6   4  -8  -5]
 [ -3   9  -8  -2 -10]
 [ -9   9   0   2   2]]


[[ -7.  -4.  -2.   2.   7.]
 [ -3.  -8.  -6.  -7.  -2.]
 [  1.   6.   4.  -8.  -5.]
 [ -3.   9.  -8.  -2. -10.]
 [ -9.   9.   0.   2.   2.]]


[[ -7.  -4.  -2.   2.   7.]
 [ -3.  -8.  -6.  -7.  -2.]
 [  1.   6.   4.  -8.  -5.]
 [ -3.   9.  -8.  -2. -10.]
 [ -9.   9.   0.   2.   2.]]


Notes:

1. Penghitungan secara aktual  dengan matriks identitas jarang dilakukan, namun ide ini berguna untuk penghitungan simbolis dan mengembangkan teori lebih lanjut.
2. Jika kita membahas matriks bukan bujursangkar, maka kita harus berhati-hati dalam menggunakan matriks identitas dengan ukuran yang benar tergantung pada orde perkaliannya. Misalnya, jika $C$ adalah matriks $2\times 3$, $I_2$ adalah identitas $2\times 2$, dan $I_3$ adalah identitas $3\times 3 $, kita akan mendapatkan hasil sebagai berikut.

$$
\begin{equation}
I_2 C = CI_3 = C
\end{equation}
$$

### Perkalian Vektor-Matrik

Salah satu kasus khusus perkalian matriks patut mendapat perhatian khusus, yaitu kasus dimana salah satu matriksnya adalah vektor. Kasus ini begitu penting sehingga lazim dibahas tersendiri dan diberi nama khusus, **perkalian matriks-vektor**. Misalkan $P$ adalah matriks  dan ukurannya adalah $n \times m$, dan $Y$ adalah vektor dengan ukuran yaitu $m \times 1$. Hasil kali $PY$ adalah vektor $n \times 1$. Hubungan antara vektor baru ini dan kolom matriks $P$ inilah yang menjadikan hal ini penting.

Berikut contoh khusus dalam hal ini

$$
\begin{equation}
P = \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]\hspace{1cm}
Y = \left[ \begin{array}{r} 2 \\ -3 \\ 4 \end{array}\right]
\end{equation}
$$

Dalam kasus perkalian matriks-vektor ini, kita dapat membentuk penghitungannya sedikit berbeda untuk lebih memahami apa yang terjadi.

$$
\begin{equation}
PY = \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]
\left[ \begin{array}{r} 2 \\ -3 \\ 4 \end{array}\right]=
2\left[ \begin{array}{r} 1 \\ 5 \\ 4 \\ 2 \end{array}\right] -
3\left[ \begin{array}{r} 3 \\ 2 \\ 2 \\ 2 \end{array}\right] +
4\left[ \begin{array}{r} -2 \\ 0 \\ -1 \\ 0 \end{array}\right] =
\left[ \begin{array}{r} -15\\ 4 \\ -2 \\ -2  \end{array}\right]
\end{equation}
$$

Ini adalah operasi yang sama yang kita lakukan sebelumnya, tetapi sekarang kita melihat bahwa perkalian ini adalah hasil penjumlahan kolom $P$ setelah terlebih dahulu mengalikan masing-masing kolom dengan elemen-elemen terkait di $Y$.

### Perkalian matrik dengan kolom-kolom

Kita dapat mengembangkan  perhitungan perkalian matriks-vektor untuk lebih memahami secara pasti apa yang dihasilkan dari perkalian matriks-matriks. Misalkan $Y$ dari perhitungan sebelumnya sebenarnya adalah kolom ketiga dari matriks $C$ ukuran $3\times 4$.

$$
\begin{equation}
C = \left[ \begin{array}{rrrr} * & * & 2 & * \\ * & * & -3 & * \\ * & * & 4 & *\end{array}\right]
\end{equation}
$$

Kolom ketiga dari perkalian $PC$ akan sama persis dengan $PY$! Kolom lain dari $PC$ akan menjadi hasil kali $P$ dengan kolom $C$ yang bersesuaian.

$$
\begin{equation}
PC = \left[ \begin{array}{rrrr} * & * & -15 & * \\ * & * & 4 & * \\* & * & -2 & *  \\ * & * & -2 & *\end{array}\right]
\end{equation}
$$


Diskusi ini menawarkan peluang  untuk mempelajari cara melakukan operasi pada bagian array NumPy menggunakan fitur yang disebut **slicing**. Mari kita buat matriks $P$ dan $C$, lalu definisikan $X$ sebagai **subarray** dari $C$. Untuk membuat subarray $C$, kita menggunakan sintaks $\texttt{C[a:b,c:d]}$. Ini akan membuat objek array yang berbentuk $(ba)\times(d-c)$ dan berisi elemen baris $a$ hingga $b-1$ dan kolom $c$ hingga $d-1$ dari $C$.
Khusunya, kami ingin $X$ menyertakan semua baris $C$, tetapi hanya kolom ketiga (yang memiliki indeks Python 2!).

In [ ]:

P = np.array([[1, 3, -2],[5, 2, 0],[4, 2, -1],[2, 2, 0]])
C = np.array([[0, 6, 2, 6],[-1, 1, -3, 4],[0, 2, 4, 8]])
X = C[0:3,2:3]
print(P,'\n')
print(C,'\n')
print(X,'\n')
print(P@X)

[[ 1  3 -2]
 [ 5  2  0]
 [ 4  2 -1]
 [ 2  2  0]] 

[[ 0  6  2  6]
 [-1  1 -3  4]
 [ 0  2  4  8]] 

[[ 2]
 [-3]
 [ 4]] 

[[-15]
 [  4]
 [ -2]
 [ -2]]


Catatan array slicing:

- Cara lain untuk memiliki  semua baris (atau semua kolom ) dari array untuk digunakan: tanpa suatu bilangan.  Pada contoh diatas, kita dapat menggunakan bari kode berikut untuk menghasilkan hasil yang sama. Silahkan diedit cell diatas
```
X = C[:,2:3]
```
- JIka hanya ingin memilih satu barus atau kolom,  silahkan coba baris kode berikut
```
X = C[:,2]
```
ini memang kode yang valid, tetapi array $X$ tidak persis seperti yang kita harapkan. Sebaliknya kita mendapatkan array dengan elemen yang benar, tetapi ukurannya tidak benar.

### Exercises

**Latihan 1:** Hitung $-2E$, $G+F$, $4F-G$, $HG$, dan $GE$ menggunakan definisi matriks berikut. Kerjakan latihan di atas kertas terlebih dahulu, kemudian periksa dengan melakukan perhitungan dengan array NumPy.

$$
\begin{equation}
E = \left[ \begin{array}{r} 5 \\ -2 \end{array}\right] \hspace{1cm}
F = \left[ \begin{array}{rr} 1 & 6 \\ 2 & 0 \\ -1 & -1 \end{array}\right] \hspace{1cm}
G = \left[ \begin{array}{rr} 2 & 0\\ -1 & 3 \\ -1 & 6 \end{array}\right] \hspace{1cm}
H = \left[ \begin{array}{rrr} 3 & 0 & 1 \\ 1 & -2 & 2 \\ 3 & 4 & -1\end{array}\right]
\end{equation}
$$

In [ ]:
## Code solution here.

**Latihan 2:** Carilah nilai $x$ dan $y$ agar persamaan ini berlaku.

$$
\begin{equation}
\left[ \begin{array}{rr} 1 & 3 \\ -4 & 2 \end{array}\right]
\left[ \begin{array}{rr} 3 & x \\ 2 & y \end{array}\right]=
\left[ \begin{array}{rr} 9 & 10 \\ -8 & 16 \end{array}\right]
\end{equation}
$$

In [ ]:
## Code solution here

**Latihan 3:** Tentukan array NumPy untuk matriks $H$ dan $G$  di bawah ini.

$$
\begin{equation}
H = \left[ \begin{array}{rrr} 3 & 3 & -1  \\ -3 & 0 & 8 \\  1 & 6 & 5 \end{array}\right]\hspace{2cm}
G = \left[ \begin{array}{rrrr} 1 & 5 & 2 & -3 \\ 7 & -2 & -3 & 0 \\ 2 & 2 & 4 & 6\end{array}\right]
\end{equation}
$$

$(a)$ Kalikan kolom kedua dan ketiga $H$ dengan baris pertama dan kedua $G$. Gunakan slice untuk membuat subarray. Apakah hasilnya ada hubungannya dengan perkalian $HG$  secara utuh?

$(b)$ Kalikan baris pertama dan kedua $H$ dengan kolom kedua dan ketiga $G$. Apakah hasil ini ada hubungannya dengan perkalian $HG$ secara utuh?


In [ ]:
## Code solution here.

**Latihan 4:** Buatlah matriks $4\times 4$ $B$ dengan elemen matrik bilangan bulat acak. Hitung matriks $P = \frac12(B+B^T)$ dan $Q = \frac12(B-B^T)$. Jalankan ulang kode Anda beberapa kali untuk mendapatkan matriks yang berbeda. Apa yang Anda perhatikan tentang $P$ dan $Q$? Jelaskan mengapa hal itu haru selalu benar.       

In [ ]:
## Code solution here.

**Latihan 5:** Sama seperti elemen matriks yang dapat berupa bilangan bulat atau bilangan real, kita juga dapat memiliki matriks yang elemennya juga merupakan matriks. **Matriks blok** adalah matriks apa pun yang telah kami tafsirkan sebagai dipartisi ke dalam **submatriks** ini. Hitung perkalian dari $HG$ dengan menggunakan$H_i$ dan $G_j$ sebagai elemen matriksnya masing-masing. Jika kita mempunyai dua matriks yang dapat dikalikan seperti biasanya, apakah ada partisi yang memungkinkan kita mengalikan menggunakan submatriks sebagai elemennya?

$$
\begin{equation}
H = \left[ \begin{array}{cc|cc} 1 & 3 & 2 & 0  \\ -1 & 0 & 3 & 3 \\ \hline 2 & 2 & -2 & 1 \\ 0 & 1 & 1 & 4 \end{array}\right] = \left[ \begin{array}{} H_1 & H_2 \\ H_3 & H_4\end{array} \right] \hspace{2cm}
G = \left[ \begin{array}{cc|c} 3 & 0 & 5 \\ 1 & 1 & -3 \\ \hline 2 & 0 & 1 \\ 0 & 2 & 1\end{array}\right] = \left[ \begin{array}{} G_1 & G_2 \\ G_3 & G_4\end{array} \right]
\end{equation}
$$

In [ ]:
## Code solution here.