## Faktorisasi LU


Kita melihat di bagian terakhir bahwa dengan dua matriks, $A$ dan $B$, dengan ukuran matrik tertentu , kita mendapatkan  matriks $C=AB$. Pada bagian ini kita membahas faktorisasi suatu matriks. Sehingga nantinya jika kita memiliki matrik $C$ maka kita akan mendapatkan dua faktor faktor matriks $A$ dan $B$.

Salah satu faktorisasi yang berkaitan erat dengan proses eliminasi disebut Faktorisasi LU. Diberikan matriks $A$, kita akan mencari matriks $L$ dan $U$ sedemikian rupa

- $LU = A$
- $L$ adalah matriks segitiga bawah dengan elemen diagonal utama sama dengan 1.
- $U$ adalah matriks segitiga atas.

Berikut adalah visualisasi dari apa yang telah kita bahas.


$$
\begin{equation}
A = \left[ \begin{array}{cccc} * & * & * & * \\ * & * & * & * \\ * & * & * & * \\ * & * & * & *  \end{array}\right]\hspace{1cm}
L = \left[ \begin{array}{cccc} 1 & 0 & 0 & 0 \\ * & 1 & 0 & 0 \\ * & * & 1 & 0 \\ * & * & * & 1 \end{array}\right]\hspace{1cm}
U = \left[ \begin{array}{cccc} * & * & * & * \\ 0 & * & * & * \\ 0 & 0 & * & * \\ 0 & 0 & 0 & *  \end{array}\right]\hspace{1cm}
\end{equation}
$$

Sebelum kita membahas cara mendapatkan $L$ dan $U$ dari matriks $A$ yang diketahui, mari kita pahami mengapa faktorisasi seperti itu berguna. Misalkan kita telah menemukan $L$ dan $U$ sehingga $A=LU$ dan kita ingin menyelesaikan sistem $AX=B$. Cara lain untuk menulis soal adalah $LUX=B$. Kita kemudian dapat mendefinisikan $Y$ lain yang tidak diketahui dengan mengatakan bahwa $UX=Y$, dan menukar sistem tunggal $AX=B$ dengan dua sistem berikut.

$$
\begin{eqnarray*}
UX & = & Y\\
LY & = & B
\end{eqnarray*}
$$

Sebenarnya kita telah menggandakan jumlah persamaan, dan kedua sistem tersebut berbentuk segitiga dan dapat diselesaikan dengan mudah dengan  cara substitusi mundur (atau maju). Contoh pertama menunjukkan gambaran  untuk sistem ini.

### Contoh 1:  Selesaikan  sistem persamaan berikut menggunakan faktorisasi LU

Kami ingin menyelesaikan sistem persamaan.

$$
\left[ \begin{array}{ccc} 3 & -1 & -2 \\ 6 & -1 & 0  \\ -3 & 5 & 20  \end{array}\right]X =
\left[ \begin{array}{c} -4 \\ -8 \\ 6  \end{array}\right]\hspace{1cm}
$$

di mana $X$ adalah vektor $3\times 1$ yang tidak diketahui. Misalkan  juga kita telah menghitung $L$ dan $U$.

$$
L = \left[ \begin{array}{ccc} 1 & 0 & 0 \\ 2 & 1 & 0  \\ -1 & 4 & 1  \end{array}\right] \hspace{2cm}
U = \left[ \begin{array}{ccc} 3 & -1 & -2 \\ 0 & 1 & 4  \\ 0 & 0 & 2  \end{array}\right]
$$


In [ ]:
import numpy as np
import laguide as lag
import scipy.linalg as sla

## Use Python to check for yourself that LU = A.

Sekarang kita tuliskan sistem $UX=Y$ dan $LY = B$. Untuk lebih jelasnya , kita mengabaikan notasi matriks sejenak dan gunakan variabel $x_1$, $x_2$, dan $x_3$ untuk elemen $X$ dan variabel $y_1$, $y_2$, dan $y_3$ untuk elemen $Y$.


$$
\begin{eqnarray*}
x_1 \hspace{2.1cm}& = & y_1\\
2x_1 + x_2 \hspace{1.1cm}& = & y_2\\
-x_1 + 4x_2 +x_3 & = & y_3 \\
\\
3y_1 - y_2 - 2y_3 & = & -4\\
y_2 + 4y_3 & = & -8\\
2y_3 & = & 6
\end{eqnarray*}
$$

Sekarang penyelesaiannya adalah tentang substitusi. Persamaan terakhir kita tahu $y_3$. Dari sana kita lakukan mundur untuk menemukan $y_2$ dan $y_1$. Lalu kita lanjutkan ke tiga persamaan pertama untuk menentukan nilai $x$ dengan cara yang sama, kali ini dimulai dengan persamaan pertama dan terus ke bawah.

### Matrik elementer

Untuk memahami bagaimana kita dapat membangun faktorisasi LU melalui eliminasi, ada baiknya kita melihat tentang langkah-langkah eliminasi yang dapat dilakukan dengan perkalian dengan matriks khusus yang disebut **matriks elementer**. Matriks elementer adalah hasil penerapan operasi $\texttt{RowScale}$ atau $\texttt{RowAdd}$ ke matriks identitas. (*Ingat bahwa penyusunan  ulang baris hanya diperlukan jika nila 0 muncul pada posisi pivot. Kami akan segera membahas pertukaran baris.*)

Sebagai contoh, mari kita terapkan salah satu operasi ini ke matriks identitas $4\times 4$.

In [ ]:
I = np.eye(4)
E = lag.RowAdd(I,1,2,-3)
print(I,'\n')
print(E)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -3.  1.  0.]
 [ 0.  0.  0.  1.]]


$E$ yang didapat adalah hasil penjumlahan -3 kali baris pertama $I$ ke baris ketiga $I$. Yang menarik dari matriks elementer $E$ adalah jika kita mengalikan matriks lain $A$ dengan $E$, hasilnya adalah matriks yang kita peroleh dengan menerapkan operasi baris yang sama ke $A$.

In [ ]:
A=np.array([[1,2,0,-1],[-1,1,-1,4],[2,13,-4,9],[-2,5,-3,13]])
print(A,'\n')
print(E@A)

[[ 1  2  0 -1]
 [-1  1 -1  4]
 [ 2 13 -4  9]
 [-2  5 -3 13]] 

[[ 1.  2.  0. -1.]
 [-1.  1. -1.  4.]
 [ 5. 10. -1. -3.]
 [-2.  5. -3. 13.]]


### Contoh 2:  Menentukan faktorisasi LU

Sekarang kita dapat melakukan eliminasi dengan menerapkan serangkaian matriks elementer $E_1$, $E_2$, $E_3$,...ke $A$. Mari kita lihat cara kerjanya untuk matriks di atas.

In [ ]:
A=np.array([[1,2,0,-1],[-1,1,-1,4],[2,13,-4,9],[-2,5,-3,13]])
I = np.eye(4)
E1 = lag.RowAdd(I,0,1,1)
E2 = lag.RowAdd(I,0,2,-2)
E3 = lag.RowAdd(I,0,3,2)
print(E3@E2@E1@A,'\n')
E4 = lag.RowAdd(I,1,2,-3)
E5 = lag.RowAdd(I,1,3,-3)
print(E5@E4@E3@E2@E1@A)

[[ 1.  2.  0. -1.]
 [ 0.  3. -1.  3.]
 [ 0.  9. -4. 11.]
 [ 0.  9. -3. 11.]] 

[[ 1.  2.  0. -1.]
 [ 0.  3. -1.  3.]
 [ 0.  0. -1.  2.]
 [ 0.  0.  0.  2.]]


Setelah menggunakan $\texttt{RowAdd}$ untuk menjadikan nilai nol di posisi tertentu, sekarang kita memiliki matrik $U$. Penulisan perkalian matriks dinyatakan seperti berikut:

$$
\begin{equation}
E_5E_4E_3E_2E_1A = U
\end{equation}
$$

Perhatikan bahwa urutan perkaliannya tidak dapat diubah. $E_1$ harus menjadi yang pertama dikalikan dengan $A$, lalu $E_2$, dan seterusnya. Sekarang mari kita sedikit memanipulasi perkalian matrik tersebut  berdasarkan sifat-sifat matriks invers.

$$
\begin{eqnarray}
A &=& (E_5E_4E_3E_2E_1)^{-1}U  \\
A &=& E_1^{-1}E_2^{-1}E_3^{-1}E_4^{-1}E_5^{-1}U  
\end{eqnarray}
$$

Oleha karena itu  $L = E_1^{-1}E_2^{-1}E_3^{-1}E_4^{-1}E_5^{-1}$.
Setiap matriks elementer invers mempunyai struktur segitiga bawah sederhana

In [ ]:
print(E3,'\n')
print(sla.inv(E3))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [2. 0. 0. 1.]] 

[[ 1. -0. -0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [-2.  0.  0.  1.]]


- Mengalikan dua matriks segitiga bawah menghasilkan matriks segitiga bawah. Lihatlah contoh berikut.

In [ ]:
L1 = np.array([[1,0,0,0],[-1,1,0,0],[2,3,1,0],[-2,3,0,1]])
L2 = np.array([[1,0,0,0],[2,1,0,0],[-5,4,1,0],[4,4,1,1]])
print(L1,'\n')
print(L2,'\n')
print(L1@L2)

[[ 1  0  0  0]
 [-1  1  0  0]
 [ 2  3  1  0]
 [-2  3  0  1]] 

[[ 1  0  0  0]
 [ 2  1  0  0]
 [-5  4  1  0]
 [ 4  4  1  1]] 

[[1 0 0 0]
 [1 1 0 0]
 [3 7 1 0]
 [8 7 1 1]]


Kita tahu bahwa matriks $E_1^{-1}E_2^{-1}E_3^{-1}E_4^{-1}E_5^{-1}$ membentuk $L $ faktor. Secara ringkas yaitu ketika kita mengalikan matriks-matriks elementer invers ini, entri-entri bukan nol pada bagian segitiga bawah tidak berubah.

In [ ]:
print(sla.inv(E5),'\n')
print(sla.inv(E4)@sla.inv(E5),'\n')
print(sla.inv(E3)@sla.inv(E4)@sla.inv(E5))

[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1.  0.]
 [ 0.  3.  0.  1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 3. 1. 0.]
 [0. 3. 0. 1.]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  3.  1.  0.]
 [-2.  3.  0.  1.]]


Elemen segitiga bawah bukan nol di $E_3^{-1}E_4^{-1}E_5^{-1}$ sama dengan elemen-elemen di $E_3^{-1}$, $E_4^{-1} $, dan $E_5^{-1}$. Artinya elemen-elemen dalam $L$ hanyalah faktor skala yang digunakan dalam penerapan $\texttt{RowAdd}$, dikalikan dengan -1. Sekarang setelah kita memahami bagaimana matriks-matriks elementer ini digabungkan untuk menghasilkan $L$, kita sebenarnya tidak perlu menyusunnya. Kita bisa menghitung $L$ dengan melakukan operasi baris dengan melacak faktor skala.

In [ ]:
L = np.array([[1,0,0,0],[-1,1,0,0],[2,3,1,-0],[-2,3,0,1]])
U = np.array([[1,2,0,-1],[0,3,-1,3],[0,0,-1,2],[0,0,0,2]])
print("L:",'\n',L,'\n',sep='')
print("U:",'\n',U,'\n',sep='')
print("LU:",'\n',L@U,sep='')

L:
[[ 1  0  0  0]
 [-1  1  0  0]
 [ 2  3  1  0]
 [-2  3  0  1]]

U:
[[ 1  2  0 -1]
 [ 0  3 -1  3]
 [ 0  0 -1  2]
 [ 0  0  0  2]]

LU:
[[ 1  2  0 -1]
 [-1  1 -1  4]
 [ 2 13 -4  9]
 [-2  5 -3 13]]


### Matrik Permutasi

Seperti yang telah kita lihat pada bagian sebelumnya, terkadang baris-baris matriks perlu disusun ulang saat melakukan eliminasi. Operasi baris ini juga dapat dilakukan dengan mengalikan matriks dengan matriks elementer. Marilah kita buat matriks $P$ dengan melakukan pertukaran baris 2 dan 3 dalam matriks $4\times 4$. Sesungguhnya, kita dapat melakukan ini dengan melakukan operasi baris yang sama pada matriks identitas.

In [ ]:
C = np.random.randint(-6,6,size=(4,4))
I = np.eye(4)
P = lag.RowSwap(I,1,2)

print("C:",'\n',C,'\n',sep='')
print("P:",'\n',P,'\n',sep='')
print("PC:",'\n',P@C,sep='')

C:
[[ 5  2 -6  1]
 [ 4  2  4  3]
 [-3  2 -3 -5]
 [ 0  1  1  3]]

P:
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]

PC:
[[ 5.  2. -6.  1.]
 [-3.  2. -3. -5.]
 [ 4.  2.  4.  3.]
 [ 0.  1.  1.  3.]]


Jika operasi baris adalah pertukaran baris, matriks elementer terkait  biasanya disebut sebagai **matriks permutasi**, dan menggunakan huruf $P$ untuk merepresentasikannya. Penting juga untuk dicatat bahwa matriks permutasi elementer adalah inversnya sendiri karena operasi pertukaran dua baris dapat dibalik dengan melakukan operasi yang sama persis. Kita dapat memeriksa bahwa $PP=I$, yang berarti $P=P^{-1}$.

In [ ]:
print(P@P)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Perhatikan bahwa jika suatu permutasi mewakili lebih dari satu pertukaran baris, maka inversnya harus mewakili pertukaran baris yang diterapkan dalam urutan terbalik.

### Contoh 3: Memfaktorkan dengan pertukaran baris

Untuk memahami bagaimana pertukaran baris dimasukkan ke dalam faktorisasi, akan sangat membantu jika kita melihat contohnya. Dalam contoh $4\times 4$ ini, kita akan menggunakan fungsi $\texttt{laguide}$ untuk melakukan eliminasi dan membangun matriks elementer. Untuk operasi $\texttt{RowAdd}$, kita akan memberi label matriks dasar dengan $L$, dan untuk operasi $\texttt{RowSwap}$ kita akan menggunakan label $P$.

In [ ]:
B = np.array([[1,2,-1,-1],[4,8,-4,2],[1,1,1,2],[3,3,4,4]])
print(B)

[[ 1  2 -1 -1]
 [ 4  8 -4  2]
 [ 1  1  1  2]
 [ 3  3  4  4]]


In [ ]:
B = lag.RowAdd(B,0,1,-4)
L1 = lag.RowAdd(I,0,1,-4)

B = lag.RowAdd(B,0,2,-1)
L2 = lag.RowAdd(I,0,2,-1)

B = lag.RowAdd(B,0,3,-3)
L3 = lag.RowAdd(I,0,3,-3)

print(B)

[[ 1.  2. -1. -1.]
 [ 0.  0.  0.  6.]
 [ 0. -1.  2.  3.]
 [ 0. -3.  7.  7.]]


In [ ]:
B = lag.RowSwap(B,1,2)
P1 = lag.RowSwap(I,1,2)

print(B)

[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0.  0.  0.  6.]
 [ 0. -3.  7.  7.]]


In [ ]:
B = lag.RowAdd(B,1,3,-3)
L4 = lag.RowAdd(I,1,3,-3)

print(B)

[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0.  0.  0.  6.]
 [ 0.  0.  1. -2.]]


In [ ]:
B = lag.RowSwap(B,2,3)
P2 = lag.RowSwap(I,2,3)

print(B)

[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  6.]]


Dalam perkalian matriks tersebut, kita telah melakukan perkalian matriks $P_2L_4P_1L_3L_2L_1B = U$, seperti yang telah dilakukan

In [ ]:
B = np.array([[1,2,-1,-1],[4,8,-4,2],[1,1,1,2],[3,3,4,4]])
U = P2@L4@P1@L3@L2@L1@B
print(U)

[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  6.]]


 Seperti yang kita lihat pada perhitungan di sel berikutnya, matriks invers $(P_2L_4P_1L_3L_2L_1)^
{-1}$ tidak memiliki struktur segitiga bawah yang tepat untuk menjadi faktor $L$. Faktanya tidak ada matriks $L$ dan $U$ dengan struktur segitiga yang benar sehingga $B=LU$

In [ ]:
possible_L = sla.inv(P2@L4@P1@L3@L2@L1)
print(possible_L)

[[1. 0. 0. 0.]
 [4. 0. 0. 1.]
 [1. 1. 0. 0.]
 [3. 3. 1. 0.]]


Meskipun matriks ini tidak memiliki struktur yang benar, kita perlu  mengatur ulang baris-barisnya untuk menghasilkan matriks segitiga bawah. Faktanya, pertukaran baris yang diperlukan di sini *sama persis* dengan yang digunakan dalam proses eliminasi.

In [ ]:
L = P2@P1@possible_L
print(L)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [3. 3. 1. 0.]
 [4. 0. 0. 1.]]


Sekarang  kita gabungkan semua ini untuk membentuk faktorisasi $B$. Eliminasi menunjukkan bahwa $B = (P_2L_4P_1L_3L_2L_1)^{-1}U$, tetapi matriks $(P_2L_4P_1L_3L_2L_1)^{-1}$ bukan segitiga bawah. Kita dapat membentuk faktor segitiga bawah dengan mengalikannya dengan matriks permutasi untuk menghasilkan pertukaran baris.

$$
P_2P_1B = P_2P_1(P_2L_4P_1L_3L_2L_1)^{-1}kamu
$$

Kita akan memberi label $P_2P_1(P_2L_4P_1L_3L_2L_1)^{-1}$ sebagai $L$, sehingga kita sekarang memiliki bentuk struktur matrik yang benar. Hasil akhirnya adalah $B=PLU$ di mana $P=(P_2P_1)^{-1}$. Untuk menghitung invers matriks permutasi, kita cukup menerapkan pertukaran baris dalam urutan terbalik, sehingga $P=P_1P_2$.

In [ ]:
P = P1@P2
print("P\n",P,'\n',sep='')
print("L\n",L,'\n',sep='')
print("U\n",U,'\n',sep='')
print("PLU\n",P@L@U,sep='')

## Note the optional argument sep='' to print eliminates the space usually included between printed items

P
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

L
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [3. 3. 1. 0.]
 [4. 0. 0. 1.]]

U
[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  6.]]

PLU
[[ 1.  2. -1. -1.]
 [ 4.  8. -4.  2.]
 [ 1.  1.  1.  2.]
 [ 3.  3.  4.  4.]]


Poin penting adalah jika pertukaran baris digunakan selama eliminasi, matriks permutasi akan diperlukan dalam faktorisasi agar $L$ memiliki struktur segitiga yang diinginkan. Oleh karena itu secara umum diharapkan $B=PLU$ di mana $P$ mewakili semua pertukaran baris yang terjadi selama proses eliminasi.

Cara lain untuk menghasilikan ini adalah dengan melakukan pertukaran baris yang diperlukan *sebelum* memulai proses eliminasi, hal tersebut tidak akan mengganggu struktur $L$. Mari kita coba!

In [ ]:
B = np.array([[1,2,-1,-1],[4,8,-4,2],[1,1,1,2],[3,3,4,4]])
B = lag.RowSwap(B,1,2)
B = lag.RowSwap(B,2,3)
print(B)

[[ 1.  2. -1. -1.]
 [ 1.  1.  1.  2.]
 [ 3.  3.  4.  4.]
 [ 4.  8. -4.  2.]]


In [ ]:
B = lag.RowAdd(B,0,1,-1)
L1 = lag.RowAdd(I,0,1,-1)

B = lag.RowAdd(B,0,2,-3)
L2 = lag.RowAdd(I,0,2,-3)

B = lag.RowAdd(B,0,3,-4)
L3 = lag.RowAdd(I,0,3,-4)

print(B)

[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0. -3.  7.  7.]
 [ 0.  0.  0.  6.]]


In [ ]:
B = lag.RowAdd(B,1,2,-3)
L4 = lag.RowAdd(I,1,2,-3)

print(B)

[[ 1.  2. -1. -1.]
 [ 0. -1.  2.  3.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  6.]]


Proses ini menunjukkan bahwa $L_4L_3L_2L_1P_2P_1B=U$. Sehingga  $(L_4L_3L_2L_1)^{-1}$ memiliki struktur yang benar, dan merupakan matriks $L$ yang sama seperti pada perhitungan sebelumnya.

In [ ]:
L = sla.inv(L4@L3@L2@L1)
print(L)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [3. 3. 1. 0.]
 [4. 0. 0. 1.]]


### Faktorisasi PLU dengan SciPy

Fungsi SciPy $\texttt{linalg}$ digunakan untuk mencari faktorisasi $PLU$ yangd disebut $\texttt{lu}$. Fungsi ini membutuhkana argumen array untuk difaktorkan, dan akan mengembalikan tiga array secara berurutan yaitu $P$, $L$, dan $U$. $\texttt{lu}$ digunak untuk menyimpan tiga array tersebut iyang akan digunakan nantinya.

In [ ]:

B = np.array([[1,2,-1,-1],[4,8,-4,2],[1,1,1,2],[3,3,4,4]])
P,L,U = sla.lu(B)

print("P\n",P,'\n',sep='')
print("L\n",L,'\n',sep='')
print("U\n",U,'\n',sep='')
print("PLU\n",P@L@U,sep='')

P
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

L
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.25        0.33333333  1.          0.        ]
 [ 0.25       -0.         -0.          1.        ]]

U
[[ 4.          8.         -4.          2.        ]
 [ 0.         -3.          7.          2.5       ]
 [ 0.          0.         -0.33333333  0.66666667]
 [ 0.          0.          0.         -1.5       ]]

PLU
[[ 1.  2. -1. -1.]
 [ 4.  8. -4.  2.]
 [ 1.  1.  1.  2.]
 [ 3.  3.  4.  4.]]


Kita mengetahui bahwa  fungsi $\texttt{lu}$ menghasilkan matriks $P$, $L$, dan $U$ sehingga $B=PLU$, namun faktornya berbeda dengan yang kita temukan menggunakan operasi baris. Perlu disadari bahwa faktorisasi $B$ menjadi $PLU$ tidaklah unik karena ada pilihan yang harus diambil di baris mana yang akan ditukar.
SciPy juga dapat digunakan untuk menyelesaikan sistem $AX=B$ dengan menggunakan faktorisasi $PLU$ dari $A$ serta juga  dengan cara substitusi maju dan mundur. Untuk melakukan ini kita menggunakan $\texttt{lu_factor}$ untuk pemfaktoran dan $\texttt{lu_solve}$ untuk melakukan substitusi.

In [ ]:
A = np.array([[1,2,-1,-1],[4,8,-4,2],[1,1,1,2],[3,3,4,4]])
X_true = np.array([[1],[0],[1],[0]])
B = A@X_true

## lu_factor returns two objects which store the information needed to reconstruct the factorization
## We store it all in a single object called 'factorization', which can then be passed to lu_solve
factorization = sla.lu_factor(A)
X_computed = sla.lu_solve(factorization,B)

print("Computed solution X:\n",X_computed,'\n',sep='')


Computed solution X:
[[ 1.]
 [-0.]
 [ 1.]
 [-0.]]



Hasil yang diperoleh dari $\texttt{lu_factor}$ tidak sama dengan hasil yang diperoleh dari $\texttt{lu}$. Mengapa????

### Latihan

**Latihan 1:** Selesaikan $AX = B$ menggunakan $A = LU $ dan $L$, $U$, dan $B$ di bawah ini. Hitung $LUX$ untuk memverifikasi jawaban Anda.

$$
\begin{equation}
A = \left[ \begin{array}{ccc} 5 & 2 & 1 \\ 5 & 3 & 0 \\ -5 & -2 & -4  \end{array}\right] \hspace{2cm}
B = \left[ \begin{array}{c} 4 \\ 7 \\ 8  \end{array}\right] \hspace{2cm}
L = \left[ \begin{array}{ccc} 1 & 0 & 0 \\ 1 & 1 & 0  \\ -1 & 0 & 1  \end{array}\right] \hspace{2cm}
U = \left[ \begin{array}{ccc} 5 & 2 & 1 \\ 0 & 1 & -1  \\ 0 & 0 & 3  \end{array}\right]
\end{equation}
$$

In [ ]:
## Koding disini

**Latihan 2:** Selesaikan $AX = B$ menggunakan $A = LU $ dan $L$, $U$, dan $B$ di bawah ini. Hitung $LUX$ untuk memverifikasi jawaban Anda.

$$
\begin{equation}
L = \left[ \begin{array}{ccc} 1 & 0 & 0 \\ -1 & 1 & 0 \\ 0 & -1 & 1  \end{array}\right] \hspace{2cm}
U = \left[ \begin{array}{ccc} 1 & -1 & 0 \\ 0 & 1 & -1  \\ 0 & 0 & 1  \end{array}\right] \hspace{2cm}
B = \left[ \begin{array}{c} 2 \\ -3 \\ 4  \end{array}\right]
\end{equation}
$$

In [ ]:
## Koding disini

**Latihan 3:** Tulis fungsi bernama $\texttt{ForwardSubstitution}$ yang akan menyelesaikan sistem segitiga bawah $LY=B$. Itu sangat membantu jika kita lihat kode untuk $\texttt{BackSubstitution}$.

In [ ]:
## Koding disini

**Latihan 4:** Misalkan $A$, $B$, dan $C$ adalah matriks berikut:

  $$
\begin{equation}
A = \left[ \begin{array}{ccc} 1 & 2 & 4 \\ 2 & 1 & 3 \\ 1 & 0 & 2  \end{array}\right] \hspace{2cm}
B = \left[ \begin{array}{ccc} 1 & 2 & 4 \\ 2 & 1 & 3  \\ 2 & 2 & 6  \end{array}\right] \hspace{2cm}
C = \left[ \begin{array}{ccc} 1 & 2 & 4 \\ 0 & -1 & -3  \\ 2 & 2 & 6  \end{array}\right]
\end{equation}
$$

$(a)$ Carilah matriks elementer $E$ sehingga $EA = B$. Verifikasi dengan perhitungan.

$(b)$ Carilah matriks elementer $F$ sehingga $FB = C$. Verifikasi dengan perhitungan.
    

In [ ]:
## Koding solusi disini

**Latihan 5:** Perhatikan matriks $3\times 3$ berikut :

$$
\begin{equation}
A = \left[ \begin{array}{rrr}  2 & 1 & 1\\  6 & 4 & 5  \\ 4 & 1 & 3 \end{array} \right]
\end{equation}
$$

$(a)$ Carilah **matriks elementer** $E_1$, $E_2$, dan $E_3$ sehingga $ E_3E_2E_1A = U $ dengan $U$ adalah matriks segitiga atas.

$(b)$ Temukan $L$ menggunakan invers dari $E_1$, $E_2$, $E_3$, dan verifikasi bahwa $ A = LU $.

In [ ]:
## Koding solusi disini

**Latihan 6:** Hitung faktorisasi $LDU$ dari matriks berikut dan verifikasi bahwa $A = LDU$.

$$
\begin{equation}
A = \left[ \begin{array}{rrr}  1 & 1 & 1\\  3 & 5 & 6  \\ -2 & 2 & 7 \end{array} \right]
\end{equation}
$$


In [ ]:
# Lakukan koding disini

**Latihan 7:** Carilah $P, L,$ dan $U$ sehingga $PA = LU$. Berdasarkan pembahasan diatas, $P$ harus berupa matriks permutasi, $L$ harus berupa matriks segitiga bawah dengan diagonal utamanya , dan $U$ harus berupa matriks segitiga atas.

$$
\begin{equation}
A = \left[ \begin{array}{rrr}  1 & 3 & 2\\  -2 & -6 & 1  \\ 2 & 5 & 7 \end{array} \right]
\end{equation}
$$
    

In [ ]:
## Koding di sini

**Latihan 8:** Gunakan SciPy untuk menghitung faktorisasi $PLU$ dari matriks $3\times 3$. Cari juga dengan  menggunakan fungsi operasi baris dengan fungsi  $\texttt{laguide}$.

In [ ]:
## Koding disini