## Matrik Invers

Pada bagian ini kita membahas matriks invers dan menjelaskan metode yang umum digunakan untuk membentuk matrik tersebut.

Oleh karena itu,  mari kita perhatikan kembali sistem persamaan linear yang ditulis dalam bentuk matriks.

$$
AX = B
$$

Sekali lagi, $A$ adalah matriks koefisien yang diketahui, $B$ adalah vektor dari data yang diketahui, dan $X$ adalah vektor yang tidak diketahui. Jika $A$, $B$, dan $X$ adalah bilangan, kita akan segera mengetahui penyelesaiannya untuk $X$  dengan cara  membagi kedua ruas persamaan dengan $A$, asalkan $A\neq0$. Pertanyaan adalah *Dapatkah kita melakukan pembagian matriks?*

Jawabannya tidak. Namun kita dapat  memahami bahwa jika $A$,$B$, dan $X$ adalah bilangan, kita membuat penyelesaiannya dengan mengalikannya dengan $1/A$. Kita hanya perlu mencari bilangan yang jika dikalikan dengan $A$ menghasilkan 1. Bilangan ini disebut invers perkalian dari $A$ dan ditulis sebagai $1/A$, asalkan $A\neq 0$.

Kita dapat memperluas ide ini pada situasi di mana $A$, $B$, dan $X$ adalah matriks. Untuk menyelesaikan sistem $AX=B$, kita perlu mengalikannya dengan matriks tertentu, yang bila dikalikan dengan $A$ akan menghasilkan matriks identitas $I$. Matriks ini dikenal sebagai **matriks invers**, dan diberi simbol $A^{-1}$.

Jika $A$ adalah matriks bujursangkar, kita mendefinisikan $A^{-1}$ (dibaca sebagai "A invers") sebagai matriks sehingga pernyataan berikut ini benar.

$$
A^{-1}A = I \hspace{3cm}AA^{-1} = I
$$

Catatan tentang invers matrik :

1. Matriksnya harus berbentuk bujur sangkar agar definisi ini masuk akal. Jika $A$ bukan bujursangkar, maka tidak mungkin keduanya
$A^{-1}A$ dan $AA^{-1}$ .
2. Tidak semua matriks mempunyai invers. Matriks yang mempunyai invers disebut matriks ****invertible**. Matriks yang tidak memiliki invers disebut matriks **non-invertible**, atau matrik **singular**.
3. Jika suatu matriks memiliki invers, maka inversnya unik.

Sekarang *jika kita mengetahui* $A^{-1}$, kita dapat menyelesaikan sistem $AX=B$ dengan mengalikan kedua ruas dengan $A^{-1}$.

$$
A^{-1}AX = A^{-1}B
$$

Maka $A^{-1}AX = IX = X$, jadi penyelesaian sistemnya adalah $X=A^{-1}B$. Sayangnya, biasanya tidak mudah untuk menemukan $A^{-1}$.

### Membentuk matrik inverse

Misalkan  $C$ adalah  matrix, dan bagaimana kita akan membentuk matrik invers

$$
C = \left[ \begin{array}{rrrr} 1 & 0 & 2 & -1 \\ 3 & 1 & -3 & 2 \\ 2 & 0 & 4 & 4 \\ 2 & 1 & -1 & -1 \end{array}\right]
$$

Mari kita bayangkan hasil kali matriks $CC^{-1}= I$ dalam bentuk kolom $C^{-1}$. Kami memfokuskan pada kolom ketiga sebagai contoh, dan memberi tanda pada elemen-elemen yang tidak diketahui tersebut dengan $y_i$. Elemen \* juga tidak diketahui, tetapi kami akan mengabaikannya untuk saat ini.

$$
CC^{-1}=
\left[ \begin{array}{rrrr} 1 & 0 & 2 & -1 \\ 3 & 1 & -3 & 2 \\ 2 & 0 & 4 & 4 \\ 2 & 1 & -1 & -1 \end{array}\right]
\left[ \begin{array}{rrrr} * & * & y_1& * \\ * & * & y_2 & * \\ * & * & y_3 & * \\ * & * & y_4 & *  \end{array}\right]=
\left[ \begin{array}{rrrr} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{array}\right]=
I
$$

Ingat sekarang bahwa $C$ dikalikan dengan kolom ketiga dari $C^{-1}$ menghasilkan kolom ketiga dari $I$. Ini merupakan sistem linier untuk menyelesaikan $y_i$.

$$
\left[ \begin{array}{rrrr} 1 & 0 & 2 & -1 \\ 3 & 1 & -3 & 2 \\ 2 & 0 & 4 & 4 \\ 2 & 1 & -1 & -1 \end{array}\right]
\left[ \begin{array}{r}  y_1 \\  y_2  \\ y_3 \\ y_4  \end{array}\right]=
\left[ \begin{array}{r}  0 \\  0  \\ 1 \\ 0  \end{array}\right]
$$


In [ ]:
import numpy as np
import laguide as lag

In [ ]:
## Solve CY = I3
C = np.array([[1,0,2,-1],[3,1,-3,2],[2,0,4,4],[2,1,-1,-1]])
I3 = np.array([[0],[0],[1],[0]])
Y3 = lag.SolveSystem(C,I3)
print(Y3)


[[-0.16666667]
 [ 0.66666667]
 [ 0.16666667]
 [ 0.16666667]]


Kolom lain dari $C^{-1}$ dapat ditemukan dengan menyelesaikan sistem serupa dengan kolom matriks identitas yang sesuai. Kita kemudian dapat membangun $C^{-1}$ dengan merangkai kolom menjadi satu matriks, dan menguji hasilnya dengan memeriksa produk $C^{-1}C$ dan $CC^{-1}$.

In [ ]:
I1 = np.array([[1],[0],[0],[0]])
I2 = np.array([[0],[1],[0],[0]])
I4 = np.array([[0],[0],[0],[1]])

Y1 = lag.SolveSystem(C,I1)
Y2 = lag.SolveSystem(C,I2)
Y4 = lag.SolveSystem(C,I4)

C_inverse = np.hstack((Y1,Y2,Y3,Y4))
print("C inverse:\n",C_inverse,'\n',sep='')
print("C inverse times C:\n",C_inverse@C,'\n',sep='')
print("C times C inverse:\n",C@C_inverse,sep='')

C inverse:
[[ 0.83333333  0.5        -0.16666667 -0.5       ]
 [-2.08333333 -1.25        0.66666667  2.25      ]
 [-0.08333333 -0.25        0.16666667  0.25      ]
 [-0.33333333  0.          0.16666667  0.        ]]

C inverse times C:
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16  1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  4.44089210e-16]
 [ 5.55111512e-17  0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

C times C inverse:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-3.33066907e-16  0.00000000e+00  1.11022302e-16  1.00000000e+00]]


Mirip dengan keadaan sebelumnya, beberapa elemen yang seharusnya nol ternyata tidak sepenuhnya nol karena kesalahan pembulatan. Sekali lagi, kita dapat menampilkan versi bulat untuk membaca hasilnya dengan lebih mudah.

In [ ]:
print(np.round(C@C_inverse,8))

[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0.  0.  0.  1.]]


Selanjutnya kita akan menulis fungsi Python untuk mendapatkan invers matriks. Dalam praktiknya, mencari invers suatu matriks adalah cara yang sangat tidak efisien dalam menyelesaikan sistem linier. Kita harus menyelesaikan sistem sebanyak $n$ hanya untuk mencari invers dari matriks $n \times n$, sehingga terlihat bahwa dibutuhkan $n$ kali  yang diperlukan untuk menyelesaikan sistem dengan eliminasi. Namun misalkan kita perlu menyelesaikan sistem linier $AX=B$ untuk dengan vektor berbeda  $B$, tetapi matriks koefisiennya sama $A$. Mungkin ini sangat menguntungkan untuk membentuk $A^{-1}$.

Untuk menjaga komputasi tetap efisien, kami ingin menghindari pengulangan operasi baris sebanyak mungkin. Untuk membuat $A^{-1}$ kita perlu menyelesaikan sistem $AX_i=Y_i$, dengan $Y_i$ adalah kolom ke $i$ dari $I$. Ini akan menghasilkan $X$, yang merupakan kolom $i$th dari $A^{-1}$. Daripada melakukan eliminasi pada setiap matriks $[A|Y_i]$ yang diperbesar, kita dapat menambah $A$ dengan seluruh matriks $I$ dan melakukan operasi yang diperlukan pada semua $Y_i$ secara bersamaan. Misalnya, jika $A$ adalah matriks $4\times 4$, kita akan memiliki matriks augmented berikut

$$
\begin{equation}
[A|I] = \left[ \begin{array}{rrrr|rrrr}
* & * & * & * & 1 & 0 & 0 & 0 \\
* & * & * & * & 0 & 1 & 0 & 0 \\
* & * & * & * & 0 & 0 & 1 & 0 \\
* & * & * & * & 0 & 0 & 0 & 1 \\
\end{array}\right]
\end{equation}
$$

Jika $A$ dapat dinverskan, modul $\texttt{RowReduction}$ dari bagian sebelumnya akan menghasilkan matriks dengan bentuk seperto  berikut.

$$
\begin{equation}
[A|I] = \left[ \begin{array}{rrrr|rrrr}
* & * & * & * & * & * & * & * \\
0 & * & * & * & * & * & * & * \\
0 & 0 & * & * & * & * & * & * \\
0 & 0 & 0 & * & * & * & * & * \\
\end{array}\right]
\end{equation}
$$

Kita dapat menggunakan lagi fungsi $\texttt{BackSubstitution}$ untuk setiap kolom disebelah kanan matrik

In [ ]:
def Inverse(A):
    # =============================================================================
    # A is a NumPy array that represents a matrix of dimension n x n.
    # Inverse computes the inverse matrix by solving AX=I where I is the identity.
    # If A is not invertible, Inverse will not return correct results.
    # =============================================================================

    # Check shape of A
    if (A.shape[0] != A.shape[1]):
        print("Inverse accepts only square arrays.")
        return
    n = A.shape[0]  # n is number of rows and columns in A

    I = np.eye(n)

    # The augmented matrix is A together with all the columns of I.  RowReduction is
    # carried out simultaneously for all n systems.
    A_augmented = np.hstack((A,I))
    R = lag.RowReduction(A_augmented)

    Inverse = np.zeros((n,n))

    # Now BackSubstitution is carried out for each column and the result is stored
    # in the corresponding column of Inverse.
    A_reduced = R[:,0:n]
    for i in range(0,n):
        B_reduced = R[:,n+i:n+i+1]
        Inverse[:,i:i+1] = lag.BackSubstitution(A_reduced,B_reduced)

    return(Inverse)

In [ ]:
print(Inverse(C))

[[ 0.83333333  0.5        -0.16666667 -0.5       ]
 [-2.08333333 -1.25        0.66666667  2.25      ]
 [-0.08333333 -0.25        0.16666667  0.25      ]
 [-0.33333333  0.          0.16666667  0.        ]]


Jika suatu matriks tidak dapat diinverskan maka proses di atas gagal. Kita harus menyadari bahwa dalam modul $\texttt{BackSubstitution}$ kita membagi elemen sepanjang diagonal utama matriks segitiga atas. Ingatlah bahwa entri-entri ini berada pada posisi pivot yang sangat penting. Jika terdapat angka nol pada paling sedikit satu posisi pivot, maka matriks tersenit  tidak dapat diinverskan.


Misalkan  setelah melakukan $\texttt{RowReduction}$ pada matriks augmented $[A|I]$ dalam modul $\texttt{Inverse}$, hasilnya adalah sebagai berikut.

$$
\begin{equation}
[A|I] = \left[ \begin{array}{rrrr|rrrr}
* & * & * & * & * & * & * & * \\
0 & 0 & * & * & * & * & * & * \\
0 & 0 & * & * & * & * & * & * \\
0 & 0 & 0 & * & * & * & * & * \\
\end{array}\right]
\end{equation}
$$

Dalam hal ini $ \texttt {BackSubstitution}$ akan gagal karena angka nol pada posisi pivot baris kedua. Oleh karena itu, $A^{-1}$ tidak ada dan kita dapat menyimpulkan bahwa $A$ tidak dapat diinverskan.

Secara umum kita menentukan apakah suatu matriks dapat diinverskan dengan melakukan langkah-langkah eliminasi dan memeriksa entri-entri pada diagonal utama dari matriks segitiga atas tersebut. Matriks  dapat diinverskan jika dan hanya jika semua elemennya tidak nol

### Invers satu sisi

Jika suatu matriks tidak berbentuk bujur sangkar, maka matriks tersebut tidak dapat dianggap dapat diinverskan menurut definisi di atas. Namun akan berguna untuk mempertimbangkan invers satu sisi. Jika $A$ adalah matriks $m\times n$, kita katakan bahwa matriks $F$ adalah **invers kanan** dari $A$ jika $AF=I_m$. Demikian pula, kita mengatakan bahwa matriks $G$ adalah **invers kiri** dari $A$ jika $GA=I_n$. Perhatikan di sini bahwa invers kanan $F$ dan invers kiri $G$ adalah matriks $n\times m$, $I_m$ adalah matriks identitas $m\times m$, dan $I_n$ adalah $n\times n$ matriks identitas.

Yang menarik untuk dicatat bahwa jika matriks $A$ memiliki *keduanya* invers kanan $F$ dan invers kiri $G$ maka keduanya harus sama karena

$$
\begin{equation}
F = I_nF = (GA)F = G(AF) = GI_m = G.
\end{equation}
$$



Invers satu sisi juga berhubungan dengan solusi sistem linier $AX=B$. Jika $A$ memiliki invers kanan $F$ maka sistem harus memiliki *setidaknya* satu solusi, $X = FB$.

$$
\begin{equation}
AX = A(FB) = (AF)B = IB = B
\end{equation}
$$

Kita akan melihat nanti bahwa sistem $AX=B$ memiliki *paling banyak* satu solusi ketika $A$ memiliki invers kiri.

### Matrik Invers dengan SciPy

Fungsi $\texttt{inv}$ digunakan untuk menghitung matriks invers dalam modul SciPy $\texttt{linalg}$. Setelah modul diimpor, penggunaan $\texttt{inv}$ sama persis dengan fungsi yang baru saja kita buat.

In [ ]:
import scipy.linalg as sla

C_inverse = sla.inv(C)
print(C_inverse)

[[ 0.83333333  0.5        -0.16666667 -0.5       ]
 [-2.08333333 -1.25        0.66666667  2.25      ]
 [-0.08333333 -0.25        0.16666667  0.25      ]
 [-0.33333333  0.          0.16666667  0.        ]]


Memberikan matriks yang tidak dapat diinverskan ke $\texttt{inv}$ akan menghasilkan kesalahan yang dimunculkan oleh interpreter Python.

### Latihan

**Latihan 1:** Selesaikan sistem persamaan berikut dengan menggunakan matrik invers

$$
\begin{eqnarray*}
2x_1 + 3x_2 + x_3 & = & 4\\
3x_1 + 3x_2 + x_3 & = & 8\\
2x_1 + 4x_2 + x_3 & = & 5
\end{eqnarray*}
$$

In [ ]:
## Koding penyelesaian disini

**Latihan 2:** Misalkan $A$ dan $B$ adalah dua matriks acak $4\times 4$. Tunjukkan dengan menggunakan Python bahwa $(AB)^{-1}=B^{-1}A^{-1}$ .

In [ ]:
## Koding penyelesaian disini

**Latihan 3:** Jelaskan mengapa $(AB)^{-1}=B^{-1}A^{-1}$ dengan menggunakan definisi yang diberikan di bagian ini.

**Latihan 4:** Selesaikan sistem $AX=B$ dengan mencari $A^{-1}$ dan menghitung $X=A^{-1}B$.

$$
A = \left[ \begin{array}{rrrr} 1 & 2 & -3 \\ -1 & 1 & -1  \\ 0 & -2 & 3  \end{array}\right] \quad\quad
B = \left[ \begin{array}{rrrr} 1  \\ 1 \\ 1  \end{array}\right]
$$    

In [ ]:
## Koding penyelesaian disini

**Latihan 5:** Carilah matriks $3 \times 3 $ $Y$ sehingga $AY = C$.

$$
A = \left[ \begin{array}{rrrr} 3 & 1 & 0 \\ 5 & 2 & 1 \\ 0 & 2 & 3\end{array}\right]\hspace{2cm}
C = \left[ \begin{array}{rrrr} 1 & 2 & 1 \\ 3 & 4 & 0 \\ 1 & 0 & 2 \end{array}\right]\hspace{2cm}
$$

In [ ]:
## Code solution here

**Latihan 6:** Misalkan $A$ adalah matriks acak $4 \times 1$ dan $B$ adalah matriks acak $1 \times 4 $. Gunakan Python untuk menunjukkan bahwa hasil kali $AB$ tidak dapat dibalik. Apakah  ini berlaku untuk dua matriks $P$ dan $Q$ sehingga $P$ adalah matriks $ n \times 1 $ dan $Q$ adalah matriks $ 1 \times n$ ? Jelaskan.

In [ ]:
## Koding penyelesaian disini

**Latihan 7:** Misalkan $A$ adalah matriks acak $3 \times 3$. Tunjukkan menggunakan Python bahwa $(A^T)^{-1} = (A^{-1})^T$. Gunakan karakteristik ini untuk menjelaskan mengapa $A^{-1}$ harus simetris jika $A$ simetris.

In [ ]:
## Koding penyelesaian disini